### ISSUE TITLE
HTML popup closed after clicking on textarea

### ISSUE THREAD

**Issue by webcreative24** [JaJuMa-GmbH/syntax-highlighter-4-page-builder#1]
Hello. First of all, thank you for that awesome extension!
I have a problem:
https://monosnap.com/file/dArSMMTg14oQo4aD7qHjNiYvvIMF9H
When I opened the HTML editor then click on the editor window html editor begin to close

Magento 2 open source 2.4.5

**Comment by webcreative24** [comment]
@JaJuMa can you please help?

**Comment by JaJuMa** [comment]
@webcreative24 We tried to reproduce on Magento 2 open source 2.4.5, but its working fine without the issue in your video.
Please check your console, maybe it gives some hint about what is going wrong.

**Comment by webcreative24** [comment]
@JaJuMa this issue caused by chrome extension called Grammarly
